# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
- task: NexusIqPipelineTask@2
  inputs:
    nexusIqService: 'iq-dev'
    organizationId: 'f2393bc70ea94449b91fbc3956ed8964'
    applicationId: 'JuiceShop_JoTest'
    stage: 'Build'
  displayName: 'npm install and build'
