trigger: none

pool: agents-dev

schedules:
- cron: '0 12 1 */1 Mon,Tue,Wed,Thu,Fri'
  displayName: Monthly 7am Build on 1st
  branches:
    include:
    - main
  always: true

jobs:
- job: build
  displayName: Build
  steps:
  - task: CmdLine@2
    displayName: Git Clone
    inputs:
      script: |
        git clone -b v14.2.0 --single-branch https://github.com/juice-shop/juice-shop.git

  - task: CmdLine@2
    displayName: Npm Install
    inputs:
      script: |
        cd juice-shop
        npm install

  - task: NexusIqPipelineTask@1
    inputs:
      nexusIqService: 'iq-dev'
      organizationId: 'f2393bc70ea94449b91fbc3956ed8964'
      applicationId: 'Js1'
      stage: 'Build'
      scanTargets: '**/*.js, **/*.ts, **/*.tgz, **/*.package.json, **/*.package-lock.json, **/*.npm-shrinkwrap.json, **/*.yarn.lock, **/*.pnpm-lock.yaml,'
      ignoreScanningError: true
