trigger: none

pool: agents-dev


jobs:
- job: build
  displayName: Build
  steps:
  - task: CmdLine@2
    displayName: Git Clone
    inputs:
      script: |
        git clone -b v14.2.0 --single-branch https://github.com/juice-shop/juice-shop.git

  - task: CmdLine@2
    displayName: Npm Install
    inputs:
      script: |
        cd juice-shop
        npm install

  - task: NexusIqPipelineTask@1
    inputs:
      nexusIqService: 'iq-dev'
      organizationId: 'f2393bc70ea94449b91fbc3956ed8964'
      applicationId: 'Js1'
      stage: 'Build'
      scanTargets: '**/*.js, **/*.ts, **/*.tgz, **/*.package.json, **/*.package-lock.json, **/*.npm-shrinkwrap.json, **/*.yarn.lock, **/*.pnpm-lock.yaml,'
      ignoreScanningError: true
